### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by kuyin** [koishijs/koishi-plugin-youdao#2]
为什么在Linux市场找不到？能上架一下吗？

**Comment by shigma** [comment]
听不明白你的问题。

**Comment by ilharp** [comment]
[Koishi Desktop](https://github.com/koishijs/koishi-desktop) 目前有面向 Linux 配布的计划哦~ 可以来这里开 issue，或加入 Koishi 用户群 [391463133](https://jq.qq.com/?_wv=1027&k=z2kKtk3N) 进行催催~
